<?php
$helper = Mage::helper('iopay_gateway');
?>

<p><img src="https://static.iopay.dev/assets/img/iopay.png" width="60"></p>
<p><?php echo $this->escapeHtml($this->__($this->getMethod()->getTitle())) ?></p>

<?php if ($this->getInfo()->getIopayPaymentId()) : ?>
    <p>
        <?php echo $this->__('Payment Id (IoPay): %s', $this->getInfo()->getIopayPaymentId()); ?>
    </p>
<?php endif; ?>

<?php if ($this->getInfo()->getAdditionalInformation('cc_number')) : ?>
    <p>
        <?php
            $creditCard     = $this->getInfo()->getAdditionalInformation('cc_number');
            $cardFormatted  =  substr($creditCard, 0, 4).'********'.substr($creditCard, -4);
            echo $this->__('Cartão: %s', $cardFormatted);
        ?>
    </p>
<p>
    <?php
    $brand          = $helper->getCardBrand(trim(str_replace(' ', '', $creditCard)));
    $brandImage     = $helper->getBrandImage($brand);
    echo '<img src="'.$brandImage.'" height="50"/>';
    ?>
</p>
<?php endif; ?>




