<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <?php if(Mage::helper('iopay_gateway')->getTaxfield() == 'iopay'): ?>
        <li>
            <label class="required" for="payment_form_<?php echo $this->getMethodCode() ?>"><em>*</em><?php echo $this->__('Informe seu CPF') ?></label>
            <div class="input-box">
                <input type="text" id="iopay_boleto_cpf" name="payment[iopay_boleto_cpf]" title="<?php echo $this->__('CPF') ?>" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getInfoData('cpf')) ?>" maxlength="16"/>
            </div>
        </li>
    <?php endif; ?>
    <?php if ($instructions = Mage::helper('iopay_gateway')->getIopayBoletoInstructions()): ?>
        <li>
            <div class="<?php echo $this->getMethodCode() ?>-instructions-content agreement-content alert alert-info">
                <?php echo nl2br($instructions) ?>
                <br>
            </div>
        </li>
    <?php endif; ?>

    <div class="d-flex align-content- flex-wrap ">
        <br/>
        <div class="p-4 ml-sm-0 ml-xl-5 ml-md-5">
            <a href="https://iopay.com.br" target="_blank" alt="IOPAY" title="IOPAY">
                <img src="https://static.iopay.dev/assets/img/iopay.png" width="60">
            </a>
        </div>
        <div class="p-4 ml-sm-0 ml-xl-5 ml-md-5 small">
            <br/>
            Essa transação é processada com tecnologias de pagamento da IOPAY.<br/>
            <i><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="width: 10px;margin-bottom: -2px"><!--! Font Awesome Pro 6.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path fill="#666666" d="M80 192V144C80 64.47 144.5 0 224 0C303.5 0 368 64.47 368 144V192H384C419.3 192 448 220.7 448 256V448C448 483.3 419.3 512 384 512H64C28.65 512 0 483.3 0 448V256C0 220.7 28.65 192 64 192H80zM144 192H304V144C304 99.82 268.2 64 224 64C179.8 64 144 99.82 144 144V192z"/></svg></i> Esta é uma conexão segura e os seus dados são protegidos com criptografia de ponta a ponta.
        </div>
    </div>
</div>