<?php
$antifraud      = false;
$antifraud_plan = Mage::helper('iopay_gateway')->getAntifraudPlan();
$antifraud_key  = Mage::helper('iopay_gateway')->getAntifraudKey();
$sessionId      = Mage::helper('iopay_gateway')->getSessionId();

if ($antifraud_plan == 'with_anti_fraud' || $antifraud_plan == 'with_anti_fraud_insurance') {
    $antifraud = true;
}
?>

<?php if ($antifraud): ?>
<script>
    window.iopayAntifraudPublicKey = "<?php echo $antifraud_key; ?>";
    window.iopaySecurityPlan = "<?php echo $antifraud_plan; ?>";
    window.iopaySessionId = "<?php echo $sessionId; ?>";

    (function() {
        var iopay = document.createElement('script');
        iopay.id = 'iopayjs'; iopay.type = 'text/javascript';iopay.async = true;
        iopay.src = 'https://checkout.iopay.com.br/assets/js/behaviour_security.js';
        var s = document.getElementsByTagName('body')[0];
        s.parentNode.insertBefore(iopay, s);
    })();
</script>
<?php endif; ?>