<?php
$helper             = Mage::helper('iopay_gateway');
$expiration_date    = $helper->convertDate($this->getInfo()->getIopayExpirationDate());
$additional         = $this->getInfo()->getAdditionalInformation();
?>

<p><?php echo $this->escapeHtml($this->__($this->getMethod()->getTitle())) ?></p>
<p><?php echo $this->__('Payment Id (IoPay): %s', $this->getInfo()->getIopayPaymentId()); ?></p>
<p><?php echo $this->__('Customer (IoPay): %s', $this->getInfo()->getIopayCustomer()); ?></p>
<p><?php echo $this->__('Token: %s', $additional['token']); ?></p>
<p><?php echo $this->__('Installments: %s', $additional['cc_installment']); ?></p>
<p><?php echo $this->__('Status: %s', $this->getInfo()->getCcStatus()); ?></p>
