<?php
$helper             = Mage::helper('iopay_gateway');
$expiration_date    = $helper->convertDate($this->getInfo()->getIopayExpirationDate());
$additional         = $this->getInfo()->getAdditionalInformation();
$creditCard         = $additional['cc_number'];
$cardFormatted      = substr($creditCard, 0, 4).'********'.substr($creditCard, -4);
$brand              = $helper->getCardBrand(trim(str_replace(' ', '', $creditCard)));
$brandImage         = $helper->getBrandImage($brand);
?>
<p><img src="https://static.iopay.dev/assets/img/iopay.png" width="60"></p>
<p><?php echo $this->escapeHtml($this->__($this->getMethod()->getTitle())) ?></p>
<p><img src="<?php echo $brandImage; ?>" height="50"/></p>
<p><?php echo $this->__('Bandeira: %s', $brand); ?></p>
<p><?php echo $this->__('Payment Id (IoPay): %s', $this->getInfo()->getIopayPaymentId()); ?></p>
<p><?php echo $this->__('Customer (IoPay): %s', $this->getInfo()->getIopayCustomer()); ?></p>
<p><?php echo $this->__('Token: %s', $additional['token']); ?></p>
<p><?php echo $this->__('Parcelamento: %s', $additional['cc_installment']); ?></p>
<p><?php echo $this->__('Status: %s', $this->getInfo()->getCcStatus()); ?></p>

